// <auto-generated />
using BLBM_ENV.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BLBM_Env.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250905084645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BLBM_ENV.Models.Baglanti", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ConnectionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("Source_DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_Port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_ServiceTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_Tur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("Target_DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target_IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target_Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target_Port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target_ServiceTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target_Tur")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SourceDeviceID");

                    b.HasIndex("TargetDeviceID");

                    b.ToTable("Baglantilar");
                });

            modelBuilder.Entity("BLBM_ENV.Models.Envanter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ClusterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IloIdracIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kabin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KabinU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RearFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTagSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcenterAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Envanterler");
                });

            modelBuilder.Entity("BLBM_ENV.Models.EnvanterDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BakirMAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceServiceTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnvanterID")
                        .HasColumnType("int");

                    b.Property<string>("FiberMAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NicID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwServiceTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WWPN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EnvanterID");

                    b.ToTable("EnvanterDetails");
                });

            modelBuilder.Entity("BLBM_ENV.Models.Vip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cluster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakineAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakineIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Network")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VipIp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Vips");
                });

            modelBuilder.Entity("BLBM_ENV.Models.Baglanti", b =>
                {
                    b.HasOne("BLBM_ENV.Models.Envanter", "SourceDevice")
                        .WithMany("AsSourceConnections")
                        .HasForeignKey("SourceDeviceID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BLBM_ENV.Models.Envanter", "TargetDevice")
                        .WithMany("AsTargetConnections")
                        .HasForeignKey("TargetDeviceID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SourceDevice");

                    b.Navigation("TargetDevice");
                });

            modelBuilder.Entity("BLBM_ENV.Models.EnvanterDetail", b =>
                {
                    b.HasOne("BLBM_ENV.Models.Envanter", "Envanter")
                        .WithMany("Details")
                        .HasForeignKey("EnvanterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envanter");
                });

            modelBuilder.Entity("BLBM_ENV.Models.Envanter", b =>
                {
                    b.Navigation("AsSourceConnections");

                    b.Navigation("AsTargetConnections");

                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
